services:
  app:
    # Comment the next line to build image locally
    # image: ghcr.io/jeremu2907/audio-converter:latest
    # Comment the following `build`, `volumes` and its attributes to run the most updated official image
    build:
       context: .
       dockerfile: dev.dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
      - ./app/.eslintrc.json:/app/.eslintrc.json
      - ./app/jsconfig.json:/app/jsconfig.json
      - ./app/next.config.mjs:/app/next.config.mjs
      - ./app/package-lock.json:/app/package-lock.json
      - ./app/package.json:/app/package.json
      - ./app/postcss.config.mjs:/app/postcss.config.mjs
      - ./app/tailwind.config.js:/app/tailwind.config.js
      - ./app/tmp:/tmp
      # - ./app/cookies.json:/app/cookies.json
    tty: true