version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./app:/app
    # entrypoint: ["/bin/bash"]
    tty: true